### PR TITLE
Merge Jinny's branch into master

### PR DESCRIPTION
**Pull request by jinnyto**
Work from during the project - Contributions listed in readme.md in master

### CODE REVIEW

**Review by aysunakarsu — COMMENTED** [review]
Reviewed

**Review by sekouu — APPROVED** [review]

**Review by ftramond — APPROVED** [review]

**Review by sekouu — APPROVED** [review]

**Comment by aysunakarsu** [comment]
Reviewed

**Review by aysunakarsu — COMMENTED** [review]
Approve

**Review by aysunakarsu — COMMENTED** [review]
Approve

**Review by aysunakarsu — APPROVED** [review]
No comment

**Pull request merged**
