### PR TITLE
Add 4 clean datasets 

### PR DESCRIPTION
**Pull request by jinnyto**
- CSV format
- Ordered by ascending date
- Region name uses 3-letter acronym from https://fr.wikipedia.org/wiki/R%C3%A9gion_fran%C3%A7aise
- Avg temp for regions normalized using surface area
Regional GDP data available only from 2010-2015

### CODE REVIEW

**Review by aysunakarsu — COMMENTED** [review]
datasets are validated

**Review by ftramond — APPROVED** [review]
Ok

**Review by sekouu — APPROVED** [review]

**Comment by aysunakarsu** [comment]
Reviewed

**Comment by aysunakarsu** [comment]
Approved

**Review by aysunakarsu — APPROVED** [review]
Reviewed

**Pull request merged**
